services:
  # PostgreSQL Service
  postgres:
    env_file:
      - .env
    image: postgres:13
    container_name: amicooked_postgres
    restart: always
    environment: 
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - "5433:5432"
    volumes:  
      - postgres_data:/var/lib/postgresql/data
      - ./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - amicooked_network
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "root", "-d", "${POSTGRES_DATABASE}"]
      timeout: 30s
      retries: 20
      interval: 3s
      start_period: 80s
  # Node. js Express Service
  api:
    env_file:
      - .env
    build: .
    container_name: amicooked_api
    restart: always
    environment: 
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - amicooked_network

volumes:
  postgres_data:  

networks:
  amicooked_network:
    driver: bridge