services:
  # MySQL Service
  mysql:
    env_file:
      - .env
    image: mysql:8.0
    container_name: amicooked_mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER:  ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports: 
      - "3307:3306"
    volumes:  
      - mysql_data:/var/lib/mysql
      - ./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - amicooked_network
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout:  20s
      retries:  10

  # Node. js Express Service
  api:
    env_file:
      - .env
    build: .
    container_name: amicooked_api
    restart: always
    environment: 
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    ports:
      - "3001:3000"
    volumes:
      - uploads:/uploads
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - amicooked_network

volumes:
  mysql_data:  
  uploads:

networks:
  amicooked_network:
    driver: bridge